#spring.application.name=Smart-LC-Portal
## Server Configuration
#server.port=8080
#
## Oracle Database Connection (Docker)
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
#spring.datasource.username=system
#spring.datasource.password=root
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#
## Hibernate Configuration
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
## Disable Spring Boot Docker Compose (Use existing DB)
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update